### ISSUE TITLE
Configure 'stan'

### ISSUE THREAD

**Issue by chshersh** [chshersh/iris#64]
Stan is a Haskell static analyser. To get the most of Haskell DX, it would be nice to configure it as well.

- [ ] Add Stan config
- [ ] Add Stan CI job
- [ ] Fix or ignore all Stan warnings

**Comment by german1608** [comment]
Hi there!

I'd like to work on this!

I built both projects (`iris` and `stan`) using GHC 8.10.7, and got the following output, using no stan config at all:

<img width="1096" alt="Screen Shot 2022-10-02 at 4 27 34 PM" src="https://user-images.githubusercontent.com/29154504/193474833-a931a892-df1d-41be-9a7c-f9900ef51528.png">

And we already have the config starting at GHC 8.8 (I'm unfamiliar if HIE are supported since this version).

https://github.com/chshersh/iris/blob/1bede5f2c7211e633c6356f03b1dc5f201326717/iris.cabal#L42-L45

I've read about `stan` a while ago, but this is the first time I actually use it. We can start with an empty `.stan.toml` file, and add config as the project grow, or you may suggest a starting point for the config. I'm happy regardless.

**Comment by chshersh** [comment]
Thanks for giving it a go!

I agree that we can start with an empty `.stan.toml` config and add things later if needeed 🙂 

The error you see is in the autogenerated by Cabal modules so we can't fix them. We can only ignore them. And this is what needs to be put in the config 🙂 

However, looks like this is impossible at the moment due to the following Stan issue:

* https://github.com/kowainik/stan/issues/399

**Comment by german1608** [comment]
Oh, I see, I didn't noted the file was autogenerated.

alright then, I'll take a look at this soon.

Thanks for your kind response.
